# @package _global_
defaults:
  - ../main@_global_
  - _self_
name: glioblastoma_omics
model:
  save_file: saved_weights2.pt
data:
  predefined_network: false
  use_causal_edges: true
  significant_ppi: false
  rna_data: Data/input_data/data2/frmt_transcriptomics.csv
  metab_data: Data/input_data/data2/frmt_metabolomics.csv
  prot_data: Data/input_data/data2/frmt_proteomics.csv
  base_network_file: human_base_network_2.graphml
causal:
  filt_rna: Data/input_data/data2/renal_cancer_gene_filt.txt
  filt_prot: Data/input_data/data2/renal_cancer_prot_filt.txt
  alpha: 0.1
  llm:
    objective: orient
    model_id: meta-llama-3.1-8b-instruct
    temperature: 0.7
    rag: true
perform_intervention: false