# @package _global_
defaults:
  - ./rcc@_global_
  - _self_
name: rcc_bn4
description: Causal Links
data:
  predefined_network: false
  use_causal_edges: true
  significant_ppi: false
  use_ppi_network: false
causal:
  llm:
    objective: orient
    model_id: meta-llama-3.1-8b-instruct
    temperature: 0.7
    rag: true
perform_intervention: false