# @package _global_
defaults:
  - ./rcc@_global_
  - _self_
name: rcc_bn9
description: No R-R or P-P links, only base network
model:
  use_metadata: false
  train_single_sample: true
  batch_size: 8
data:
  predefined_network: false
  use_causal_edges: false
  significant_ppi: false
  use_ppi_network: false
causal:
  rna_method: llm
  prot_method: llm
  llm:
    objective: None
    model_id: meta-llama-3.1-8b-instruct
    temperature: 0.7
    rag: true
pathway_analysis:
  enabled: false
intervention:
  enabled: false
debug: true