# @package _global_
defaults:
  - ./rcc@_global_
  - _self_
name: rcc_bn7
description: Causal links with Significant PPI links
model:
  use_metadata: true
  train_single_sample: true
  batch_size: 8
data:
  predefined_network: false
  use_causal_edges: true
  significant_ppi: true
  use_ppi_network: true
  metadata_file: Data/input_data/KidneyTumorData/frmt_metadata.pkl
causal:
  llm:
    objective: orient
    model_id: meta-llama-3.1-8b-instruct
    temperature: 0.7
    rag: true
pathway_analysis:
  enabled: false
intervention:
  enabled: false
debug: true