# @package _global_
defaults:
  - ./rcc@_global_
  - _self_
name: rcc_bn7
description: Causal links with Significant PPI links
data:
  predefined_network: false
  use_causal_edges: true
  significant_ppi: true
  use_ppi_network: true
causal:
  llm:
    objective: orient
    model_id: meta-llama-3.1-8b-instruct
    temperature: 0.7
    rag: true
intervention:
  enabled: true
  sample: 1
  mult: 1.2
  pathway: Central carbon metabolism in cancer
perform_intervention: false