# @package _global_
defaults:
  - ./rcc@_global_
  - _self_
name: rcc_bn5
description: Random links
model:
  use_metadata: true
  train_single_sample: true
  batch_size: 8
data:
  predefined_network: false
  use_causal_edges: false
  significant_ppi: false
  use_ppi_network: false
  random_edges: true
  n_random_edges_rna: 162
  n_random_edges_prot: 231
  metadata_file: Data/input_data/KidneyTumorData/frmt_metadata.pkl
pathway_analysis:
  enabled: false
intervention:
  enabled: false
debug: true