---
name: base_default
description: Base config description
model:
  train: true
  epochs: 5
  train_test_ratio: 0.7
  train_single_sample: false
  save_file: saved_weights.pt
  runs: 1
  prot_loss: 0
  metab_loss : 1
  drop_edges: 0.5
data:
  dir: Data/
  org_name: human
  random_edges: false
  n_random_edges_rna: 162
  n_random_edges_prot: 231
  predefined_network: false
  use_ppi_network: true
  use_causal_edges: true
  significant_ppi: true
  rna_data: Data/input_data/rna_df.csv
  metab_data: Data/input_data/metab_df.csv
  prot_data: Data/input_data/prot_df.csv
  base_network_file: human_base_network.graphml
causal:
  alpha: 0.05
  rna_method: fci
  prot_method: fci
  rna_indep_test: mv_fisherz
  prot_indep_test: mv_fisherz
  replaceNanRNA: false
  replaceNanProt: true
  rna_keep:
  prot_keep:
  llm:
    objective: # check, orient_check, orient, None
    model_id: meta-llama-3.1-8b-instruct
    temperature: 0.7
    rag: true
intervention:
  enabled: true
  sample: 1
  mult: 1.2
  pathway: Central carbon metabolism in cancer
output:
  save_dir: output/